server:
  port: 9191

spring:
 application:
  name: API-GATEWAY
 cloud:
   gateway:
     routes:
       - id: CINEMA-SERVICE
         uri: lb://CINEMA-SERVICE
         predicates:
           - Path=/cinemas/**
       - id: EMPLOYEE-SERVICE
         uri: lb://EMPLOYEE-SERVICE
         predicates:
           - Path=/employees/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
